name: CPS
version: 1.0
api: [3.0.0, 4.0.0]
author: iRainDrop
main: CPS\Main
description: KB Modifier
commands:
  cps:
    usage: "§cUsage: /cps <on/off>"
    description: Enable/Disable your CPS Counter popup
