# How the Popup should Display for Players.
CPS Popup: "§c§lCPS: §r§a"
# Enable the Popup for players automatically when they join.
On Join: true
# Message to send to players with cps.alerts permission.
CPS Alerts: "§7[§cAlerts§7] §b{playername} §eis clicking §c{cps} §eCPS"
# How long in between each CPS Alert
CPS Alert Cooldown: 5
# CPS Limit, all other hits after this amount will be CANCELLED!
CPS Limit: 20
# Amount of CPS before the Alerts are triggered.
Amount of CPS: 15
# Popup enabled message.
Enabled Popup: "§aYour CPS popup has been Enabled."
# Popup disabled message.
Disabled Popup: "§cYour CPS popup has been Disabled."
